### ISSUE TITLE
Deriving Dss from Lss

### ISSUE THREAD

**Issue by ShahriarHooshmand** [DallasTrinkle/Onsager#3]
Thanks very much for the comprehensive manual. I've got a question regarding the Si in FCC Ni and in particular transforming the Lss to Dss in vacancy mediated diffusion. As it is indicated in the corresponding paper, Dss should be multiplied by Cs*Cv/KT. I am not sure how the Cs and Cv are defined here. The conversion term used in the Si in Ni example is [conv/KT] in which [conv=1e3*0.1/volume], however in the hcp workbook, Vcon is defined as [Vcon=1e-8*exp[ (entropy-Ef)/(KT) ] ] and there is no atomic volume involved here. Besides, in the "Diffusion of Si impurities in Ni under stress: A first-principles study" paper, [Dss=KT/V * Lss] and it seems that KT/V is the conversion factor. So, I am little confused about what conversion factor should we multiply by the Lss output quantity of Onsager code for both FCC and HCP system to get the diffusivity in m^2/s?

**Comment by DallasTrinkle** [comment]
Thanks for the question; there are a few issues to consider here.

* The units of the output are the units of the input. What that means is: (1) distance correspond to the units chosen in the underlying Crystal object, and (2) time correspond to the units chosen in the rate prefactors given to the Onsager calculator. For (1), we might define the Crystal where a0 is given in nanometers, or possibly Angstroms; to convert distances to m, there will be factors of 10^-9 or 10^-10, correspondingly. Similarly, we often write down rates in THz, which then gives factors of 10^12 to convert to s^-1. As one example, if a Crystal has a0 in nm, and the rates are input in THz to the Onsager calculator, the output will be in nm^2 THz, which is 10^(-7-7+12) cm^2/s = 10^-2 cm^2/s.
* The Onsager calculator *does not know* what the solute and vacancy concentrations are; in the model, these are independent functions. If you have a specific solute or vacancy concentration in mind (e.g., the equilibrium vacancy concentration at a given T, and the solute concentration in a particular alloy), you can use those. It also *does not know* what your temperature is (it only knows about rates!), which is why you also need to provide that after.
* When you define L, it can have a factor of volume per atom *depending on how you want to define* the chemical potential: L grad mu gives a flux, and so if mu is going to be per volume, then you will have a volume factor in L. This is what is happening in the Ni-Si example; the 10^30 factor is because the volume is defined in A^3, and the comparison to previous calculations used distances in m.
* Remember that the code is designed to give L, not D. Converting to Ds involves additional thermodynamic information. In the dilute limit, this is particularly easy, because the chemical potential has a very easy form based on an ideal solution. In the case of the vacancy mediated diffuser, this eliminates the "extra" factor of Cs/kT that you would need to include to explicitly get Lss (but not the factor of Cv).

I hope this helps clarify what output the code produces, and how to convert to "useful" units.

**Comment by DallasTrinkle** [comment]
I think this suggests, in the end, the need to add some explicit documentation (possibly in the README?) about putting together the inputs for calculating Onsager coefficients and interpreting the outputs (including transforming into solute diffusivity).

**Comment by DallasTrinkle** [comment]
Opened an enhancement request issue to formally add this documentation.

**Comment by ShahriarHooshmand** [comment]
Dear Prof. Trinkle,


Many thanks for your email and very helpful information. So as a conclusion, with the assumption that we started with Angstrom in crystal lattice and the Lss outputted from vacancy mediated diffuser, the steps I took to derive Dss in m^2/s would be as follows:


Dss= Lss*10^(-8) * Cv


I assume that in the dilute limit, Cv would be equal to:  [Cv=exp(entropy)*exp(-energy/(KT))] (Please correct me if I am wrong about Cv), in which entropy and energy are the vacancy formation entropy and energy, respectively and this would be regardless of the crystal system (works for both FCC and HCP systems). I really appreciate your help and very helpful directions.


Thanks,

-Shahriar

________________________________

[The Ohio State University]
Mohammad Shahriar Hooshmand
Graduate Research Associate
Applied Mechanics and Materials Engineering
The Ohio State University, Columbus, OH 43210
(614) 292-6446 Office
hooshmand.1@osu.edu<mailto:hooshmand.1@osu.edu> http://u.osu.edu/hooshmand.1/

________________________________


________________________________

**Comment by DallasTrinkle** [comment]
That's correct, assuming *global thermodynamic equilibrium* for the vacancies.

I've put in a new notebook that can be seen in the documentation: [Input/Output](https://dallastrinkle.github.io/Onsager/InputOutput.html). If you get a chance, please look through it, and feel free to let me know if you have any comments.

**Comment by ShahriarHooshmand** [comment]
Dear Prof. Trinkle,


Thanks very much for the comprehensive and very helpful documentation. It helped a lot and I really appreciate your support. I have only found a tiny point which I assume to be a typo in "In[48]" for vacancy diffusion that I think the omega2 energy should be "0.25" in the code rather than "0.5", is that right?


fivefreqdata = {
    'v:+0.000,+0.000,+0.000': [1., 0.],
    's:+0.000,+0.000,+0.000': [1., 0.],
    's:+0.000,+0.000,+0.000-v:+0.000,-1.000,+0.000': [1., -0.25],
    'omega0:v:+0.000,+0.000,+0.000^v:+0.000,+1.000,+0.000': [10., 1.],
    'omega1:s:+0.000,+0.000,+0.000-v:+1.000,+0.000,-1.000^v:+1.000,+1.000,-1.000': [10., 0.5],
    'omega1:s:+0.000,+0.000,+0.000-v:+1.000,-1.000,+0.000^v:+1.000,+0.000,+0.000': [20., 0.875],
    'omega1:s:+0.000,+0.000,+0.000-v:-1.000,+1.000,+0.000^v:-1.000,+2.000,+0.000': [20., 0.875],
    'omega1:s:+0.000,+0.000,+0.000-v:+0.000,+1.000,+0.000^v:+0.000,+2.000,+0.000': [20., 0.875],
    'omega2:s:+0.000,+0.000,+0.000-v:+0.000,-1.000,+0.000^s:+0.000,+0.000,+0.000-v:+0.000,+1.000,+0.000':
    [10., 0.5]
}



Thanks,

-Shahriar


________________________________

[The Ohio State University]
Mohammad Shahriar Hooshmand
Graduate Research Associate
Applied Mechanics and Materials Engineering
The Ohio State University, Columbus, OH 43210
(614) 292-6446 Office
hooshmand.1@osu.edu<mailto:hooshmand.1@osu.edu> http://u.osu.edu/hooshmand.1/

________________________________


________________________________

**Comment by DallasTrinkle** [comment]
That's correct: there's a typo there. Thanks for finding it!

**Comment by ShahriarHooshmand** [comment]
Dear Prof. Trinkle,


Thanks very much and my apologies for not including this in the previous email. Just about the same input part, for omega3 and omega4, why is it considered as 1-0.25/2 = 0.875 (eV).? [why we divided the binding energy by 2?] For example, if we calculate the omega3(the particular jump which is from the first shell of solute to the thermodynamic range) using VASP equal to 0.6 eV with the binding energy of -0.25, shouldn't we input the energy as 0.6-0.25=0.35 for all other three omega1(actually omega3/-4) jumps? I was just comparing the jumps with the one in NiSi example in manual and PRB paper(https://journals.aps.org/prb/pdf/10.1103/PhysRevB.90.024306) and wondering if there is any simplifying assumption (because of a factor of 2 in 1-0.25/2) in considering only one shell compared to the 3rd shell in PRB.

Thanks,
-Shahriar
________________________________

[The Ohio State University]
Mohammad Shahriar Hooshmand
Graduate Research Associate
Applied Mechanics and Materials Engineering
The Ohio State University, Columbus, OH 43210
(614) 292-6446 Office
hooshmand.1@osu.edu<mailto:hooshmand.1@osu.edu> http://u.osu.edu/hooshmand.1/

________________________________


________________________________

**Comment by DallasTrinkle** [comment]
That is just a linearized interpolation of migration barrier (LIMB) assumption; it is typically a good approximation. It's not required at all; I simply used it in this example to produce a "physically reasonable" barrier. The idea is that that transition state energy is the energy barrier for vacancy diffusion without any solutes plus the average of the initial and final state energies.

**Comment by ShahriarHooshmand** [comment]
That makes sense. For the particular calculations that I did, the LIMB approximation gives 0.541 eV and my DFT calculations for omega3 gave the barrier of 0.477eV (added to the binding energy of 0.008eV gives 0.477+0.008=0.485eV) which is close to the 0.541eV LIMB approximation. So, then we can use either of DFT directly calculated omega3 or LIMB approximation for diffusion calculations.


Thanks again and I really appreciate your help.

-Shahriar


________________________________

[The Ohio State University]
Mohammad Shahriar Hooshmand
Graduate Research Associate
Applied Mechanics and Materials Engineering
The Ohio State University, Columbus, OH 43210
(614) 292-6446 Office
hooshmand.1@osu.edu<mailto:hooshmand.1@osu.edu> http://u.osu.edu/hooshmand.1/

________________________________


________________________________
